# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-03-26 19:09
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('hhands', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DHUtilization',
            fields=[
                ('drug_u_id', models.AutoField(primary_key=True, serialize=False)),
                ('service_year', models.CharField(blank=True, max_length=20, null=True)),
                ('service_quarter', models.IntegerField(blank=True, null=True)),
                ('quarter_begin', models.CharField(blank=True, max_length=20, null=True)),
                ('quarter_begin_date', models.DateTimeField(blank=True, null=True)),
                ('supression_used', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DRreimbursements',
            fields=[
                ('dr_r_id', models.AutoField(primary_key=True, serialize=False)),
                ('units_reimbursed', models.IntegerField(blank=True, null=True)),
                ('number_of_rx', models.IntegerField(blank=True, null=True)),
                ('total_amt_reimbursed', models.DecimalField(blank=True, decimal_places=4, max_digits=13, null=True)),
                ('mcd_amt_reimbursed', models.DecimalField(blank=True, decimal_places=4, max_digits=13, null=True)),
                ('non_mcd_amt_reimbursed', models.DecimalField(blank=True, decimal_places=4, max_digits=13, null=True)),
                ('service_state', models.CharField(blank=True, max_length=45, null=True)),
                ('s_latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('s_longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('s_location', models.CharField(blank=True, max_length=50, null=True)),
                ('dr_u', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drugs_reimbursements', to='hhands.DHUtilization')),
            ],
        ),
        migrations.CreateModel(
            name='DrugsHeader',
            fields=[
                ('m_dr_id', models.AutoField(primary_key=True, serialize=False)),
                ('m_utilization_type', models.CharField(blank=True, max_length=45, null=True)),
                ('labeler_code', models.CharField(blank=True, max_length=20, null=True)),
                ('product_code', models.CharField(blank=True, max_length=20, null=True)),
                ('package_size', models.IntegerField(blank=True, null=True)),
                ('product_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('md_create_date', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user', models.Model),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='dhutilization',
            name='m_dr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drugs_utilization', to='hhands.DrugsHeader'),
        ),
    ]
