# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-03-12 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hhands', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrugsHeader',
            fields=[
                ('m_dr_id', models.AutoField(primary_key=True, serialize=False)),
                ('m_utilization_type', models.CharField(blank=True, max_length=45, null=True)),
                ('labeler_code', models.CharField(blank=True, max_length=20, null=True)),
                ('product_code', models.CharField(blank=True, max_length=20, null=True)),
                ('package_size', models.IntegerField(blank=True, null=True)),
                ('product_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('md_create_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
