# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-03-12 21:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hhands', '0002_drugsheader'),
    ]

    operations = [
        migrations.CreateModel(
            name='DHUtilization',
            fields=[
                ('drug_u_id', models.IntegerField(primary_key=True, serialize=False)),
                ('service_year', models.CharField(blank=True, max_length=20, null=True)),
                ('service_quarter', models.IntegerField(blank=True, null=True)),
                ('quarter_begin', models.CharField(blank=True, max_length=20, null=True)),
                ('quarter_begin_date', models.DateTimeField(blank=True, null=True)),
                ('supression_used', models.CharField(blank=True, max_length=20, null=True)),
                ('m_dr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DHUtilization', to='hhands.DrugsHeader')),
            ],
        ),
    ]
