# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-03-12 22:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hhands', '0003_dhutilization'),
    ]

    operations = [
        migrations.CreateModel(
            name='DRreimbursements',
            fields=[
                ('dr_r_id', models.AutoField(primary_key=True, serialize=False)),
                ('units_reimbursed', models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True)),
                ('number_of_rx', models.IntegerField(blank=True, null=True)),
                ('total_amt_reimbursed', models.DecimalField(blank=True, decimal_places=4, max_digits=13, null=True)),
                ('mcd_amt_reimbursed', models.DecimalField(blank=True, decimal_places=4, max_digits=13, null=True)),
                ('non_mcd_amt_reimbursed', models.DecimalField(blank=True, decimal_places=4, max_digits=13, null=True)),
                ('service_state', models.CharField(blank=True, max_length=45, null=True)),
                ('s_latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('s_longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('s_location', models.CharField(blank=True, max_length=50, null=True)),
                ('dr_u', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DRreimbursements', to='hhands.DHUtilization')),
            ],
        ),
    ]
