# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-03-13 01:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hhands', '0004_drreimbursements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dhutilization',
            name='drug_u_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
