# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-03-13 02:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hhands', '0005_auto_20190312_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drreimbursements',
            name='units_reimbursed',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
