# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-03-25 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hhands', '0008_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drugsheader',
            name='md_create_date',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
