# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-03-28 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hhands', '0009_auto_20190325_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dhutilization',
            name='quarter_begin',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='dhutilization',
            name='quarter_begin_date',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
