# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-03-28 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hhands', '0010_auto_20190328_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drreimbursements',
            name='mcd_amt_reimbursed',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='drreimbursements',
            name='non_mcd_amt_reimbursed',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='drreimbursements',
            name='s_latitude',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='drreimbursements',
            name='s_longitude',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='drreimbursements',
            name='total_amt_reimbursed',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='drreimbursements',
            name='units_reimbursed',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
