# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-04-23 22:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hhands', '0011_auto_20190328_1428'),
    ]

    operations = [
        migrations.CreateModel(
            name='hcp_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('F_Name', models.CharField(blank=True, db_column='F_Name', max_length=45, null=True)),
                ('L_Name', models.CharField(blank=True, db_column='L_Name', max_length=45, null=True)),
                ('Email', models.CharField(blank=True, db_column='Email', max_length=45, null=True)),
                ('Work_Number', models.CharField(blank=True, db_column='Work_Number', max_length=20, null=True)),
                ('FAX_Number', models.CharField(blank=True, db_column='FAX_Number', max_length=20, null=True)),
                ('cell_number', models.CharField(blank=True, db_column='CELL_Number', max_length=20, null=True)),
                ('NPI_Number', models.CharField(blank=True, db_column='NPI_Number', max_length=20, null=True)),
                ('speciality', models.CharField(blank=True, max_length=200, null=True)),
                ('hcp_office_name', models.CharField(blank=True, db_column='hcp_Office_name', max_length=2000, null=True)),
                ('hcp_address', models.CharField(blank=True, max_length=1000, null=True)),
                ('hcp_city', models.CharField(blank=True, max_length=200, null=True)),
                ('hcp_state', models.CharField(blank=True, max_length=200, null=True)),
                ('hcp_zip', models.CharField(blank=True, max_length=20, null=True)),
                ('hcp_country', models.CharField(blank=True, db_column='hcp_Country', max_length=50, null=True)),
                ('hcp_service_count', models.IntegerField(blank=True, null=True)),
                ('hcp_beneficiary_count', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'hcp_data',
                'managed': False,
            },
        ),
    ]
