# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-04-26 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hhands', '0012_hcp_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='DRReimTotals',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('service_state', models.CharField(blank=True, max_length=45, null=True)),
                ('total_amt_reimbursed', models.IntegerField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
