# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-05-03 21:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hhands', '0002_auto_20190326_1909'),
        ('hhands', '0013_drreimtotals'),
    ]

    operations = [
    ]
